spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://*:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 8999